spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: ""
            client-secret: ""
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            scope:
              - openid
              - profile
              - email
          kakao:
            client-name: Kakao
            client-id: ""
            client-secret:
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - account_email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=select_account
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
