spring:
  profiles:
    active:
      - oauth2-client
      - jwt # jwt, opaquetoken
  datasource:
    url: jdbc:h2:mem:authorization
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
