spring:
  profiles:
    active: jwt # jwt, opaquetoken
  datasource:
    url: jdbc:h2:mem:authorization
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    root: info
